version: '3.9'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - ./postgres/:/var/lib/postgresql/data
  
  flask_app:
    build:
      target: flask
    container_name: flask-app
    depends_on:
      - db
    command: >
      sh -c "python migration_script.py && python app.py"

  lab_app: 
    image: httpd:latest
    container_name: my-apache-app
    volumes:
      - ./lab_app/Web_Project-main/:/usr/local/apache2/htdocs

  nginx:
    build:
      context: .
      target: final
    ports:
      - "80:80"
    depends_on:
      - flask_app
      - lab_app
